<x-layouts.app title="Detalle de pedido"><div class="page-heading"><div><strong class="order-folio order-folio-detail">Folio {{ $order->order_number }}</strong><h1>{{ $order->customer_name }}</h1><p class="muted">{{ $order->customer_phone }} · {{ $order->scheduled_date->format('d/m/Y') }} a las {{ substr($order->scheduled_time,0,5) }}</p></div><span class="tag {{ $order->status }}">{{ str_replace('_',' ',$order->status) }}</span></div><div class="two-columns"><section><div class="card"><h2>Detalle de la comanda</h2>@foreach($order->items as $i)<div class="order-line {{ $i->is_cancelled?'canceled':'' }}"><div class="row-between"><strong>{{ $i->quantity }} × {{ $i->product_name }}</strong><b>${{ number_format($i->quantity*$i->unit_price,2) }}</b></div>@if($i->product_description)<p class="muted tiny">{{ $i->product_description }}</p>@endif
@foreach($i->selected_options ?? [] as $option)<p class="muted tiny">{{ isset($option['group'])?$option['group'].': ':'' }}{{ $option['quantity'] }} × {{ $option['name'] }}</p>@endforeach<p class="muted">{{ $i->kitchen_notes }}</p>@if($i->is_cancelled)<span class="tag cancelado">Partida cancelada</span>@endif</div>@endforeach<div class="total-row"><span>Envío: ${{ number_format($order->delivery_cost,2) }}</span><strong>${{ number_format($order->total,2) }}</strong></div><div class="row-between"><span>Pagado neto: ${{ number_format($order->amount_paid,2) }}</span><b>Saldo: ${{ number_format($order->balance_due,2) }}</b></div></div><div class="card"><h2>Entrega y seguimiento</h2>@include('partials.production-release',['o'=>$order])<p>{{ ucfirst($order->delivery_type) }} · {{ $order->delivery_address ?: 'Recoger en sucursal' }}</p><p class="muted">Repartidor: {{ $order->driver?->name ?? 'Sin asignar' }}</p>@can('dispatch.manage')@if($order->delivery_type==='domicilio' && !in_array($order->status,['cancelado','entregado']))<form action="{{ url('/pedidos/'.$order->id.'/repartidor') }}" method="POST" class="filter-bar">@csrf<label>Repartidor<select name="delivery_driver_id" required><option value="">Seleccionar</option>@foreach($drivers as $d)<option value="{{ $d->id }}" @selected($order->delivery_driver_id===$d->id)>{{ $d->name }}</option>@endforeach</select></label><button class="secondary">Asignar</button></form>@endif
@endcan</div>
@can('orders.edit')@if(!in_array($order->status,['cancelado','entregado']))<details class="card"><summary>Modificar notas y costo de envío</summary><form action="{{ url('/pedidos/'.$order->id.'/editar') }}" method="POST" class="form-stack">@csrf
@foreach($order->items->where('is_cancelled',false) as $i)<label>{{ $i->product_name }}<textarea name="notes[{{ $i->id }}]" maxlength="1000">{{ $i->kitchen_notes }}</textarea></label>@endforeach<label>Costo de envío<input name="delivery_cost" type="number" min="0" step="0.01" value="{{ $order->delivery_cost }}" required></label><button class="secondary">Guardar y enviar modificación</button></form></details>@endif
@endcan
@can('orders.cancel')@if(!in_array($order->status,['cancelado','entregado']))<details class="card"><summary>Cancelación parcial o total</summary><p class="muted tiny">Al confirmar, se registra la devolución del excedente pagado por los métodos originales. Realiza también la devolución física o bancaria al cliente.</p><form method="POST" action="{{ url('/pedidos/'.$order->id.'/cancelar') }}" class="form-stack" x-data @submit="if(!confirm('¿Confirmar la cancelación y registrar el reembolso correspondiente?')) $event.preventDefault()">@csrf<label>Partida<select name="item_id"><option value="">Cancelar todo el pedido</option>@foreach($order->items->where('is_cancelled',false) as $i)<option value="{{ $i->id }}">{{ $i->quantity }} × {{ $i->product_name }}</option>@endforeach</select></label><label>Motivo<input name="reason" required minlength="5" maxlength="255"></label><button class="danger">Confirmar cancelación</button></form></details>@endif
@endcan</section><aside>
@can('pos.sell')@if($order->balance_due>0 && $order->status!=='cancelado')<div class="card"><h2>Registrar abono</h2><form method="POST" action="{{ url('/pedidos/'.$order->id.'/pago') }}">@csrf<input type="hidden" name="key" value="{{ $paymentKey }}"><label>Método<select name="method"><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option></select></label><label>Importe a aplicar<input name="amount" type="number" min="0" max="{{ $order->balance_due }}" step="10" required></label><button class="primary full">Registrar pago →</button></form></div>@endif
@endcan<div class="card"><h2>Historial de pagos</h2>@forelse($order->payments as $p)<div class="order-line"><div class="row-between"><span>{{ ucfirst($p->payment_method) }}</span><b>${{ number_format($p->amount,2) }}</b></div><small class="muted">{{ $p->created_at->format('d/m/Y H:i') }} · {{ $p->is_advance?'Anticipo':'Pago' }}</small></div>@empty<p class="muted">Sin pagos registrados.</p>@endforelse
@foreach(\Illuminate\Support\Facades\DB::table('order_refunds')->where('order_id',$order->id)->get() as $refund)<div class="notice error">Reembolso {{ $refund->payment_method }}: ${{ number_format($refund->amount,2) }}<p>{{ $refund->reason }}</p></div>@endforeach
@can('orders.reprint')<form method="POST" action="{{ url('/pedidos/'.$order->id.'/reimprimir') }}">@csrf<button class="secondary full">Imprimir comprobantes</button></form>@endcan</div>@if($order->cancellation_reason)<div class="notice error">Última cancelación: {{ $order->cancellation_reason }}</div>@endif</aside></div></x-layouts.app>

