<x-layouts.app title="Reportes">
<div class="page-heading"><div><span class="eyebrow">EL PULSO DE TU NEGOCIO</span><h1>{{ $report['title'] }}</h1><p class="muted">{{ $report['description'] }}</p></div><div class="filter-bar no-print"><a class="primary" href="{{ route('reports', array_merge($f,['export'=>'xlsx'])) }}">Exportar a Excel</a><button class="secondary" x-data @click="window.print()">Imprimir</button></div></div>
<nav class="filter-bar no-print" aria-label="Tipos de reporte">@foreach($types as $key=>$label)<a class="{{ $f['report']===$key?'primary':'secondary' }}" href="{{ route('reports',['report'=>$key]) }}" @if($f['report']===$key) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
<form class="filter-bar no-print" action="{{ route('reports') }}"><input type="hidden" name="report" value="{{ $f['report'] }}">
<label>Desde {{ in_array($f['report'],['production','balances'])?'(entrega)':'' }}<input type="date" name="from" value="{{ $f['from'] }}" @required($f['report']!=='balances')></label><label>Hasta<input type="date" name="to" value="{{ $f['to'] }}" @required($f['report']!=='balances')></label>
@if($f['report']==='production')<label>Estado<select name="state">@foreach($states as $key=>$label)<option value="{{ $key }}" @selected($f['state']===$key)>{{ $label }}</option>@endforeach</select></label><label>Área<select name="area"><option value="">Todas</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected($f['area']==$area->id)>{{ $area->name }}</option>@endforeach</select></label>@endif
@if($f['report']==='balances')<label>Entregas<select name="bucket">@foreach(['all'=>'Todas','overdue'=>'Atrasadas','today'=>'Hoy','future'=>'Futuras'] as $key=>$label)<option value="{{ $key }}" @selected($f['bucket']===$key)>{{ $label }}</option>@endforeach</select></label>@endif
@if($f['report']==='payments')<label>Método<select name="method"><option value="">Todos</option>@foreach(['efectivo','transferencia','tarjeta'] as $method)<option value="{{ $method }}" @selected($f['method']===$method)>{{ ucfirst($method) }}</option>@endforeach</select></label><label>Cajero del turno<select name="cashier"><option value="">Todos</option>@foreach($cashiers as $cashier)<option value="{{ $cashier->id }}" @selected($f['cashier']==$cashier->id)>{{ $cashier->name }}</option>@endforeach</select></label>@endif
<button class="primary">Consultar</button><a class="secondary" href="{{ route('reports',['report'=>$f['report']]) }}">Restablecer</a></form>
<div class="filter-bar no-print">@foreach(['Hoy'=>[today(),today()],'Mañana'=>[today()->addDay(),today()->addDay()],'Esta semana'=>[today()->startOfWeek(),today()->endOfWeek()],'Este mes'=>[today()->startOfMonth(),today()->endOfMonth()]] as $label=>$dates)<a class="secondary" href="{{ route('reports',array_merge($f,['from'=>$dates[0]->toDateString(),'to'=>$dates[1]->toDateString()])) }}">{{ $label }}</a>@endforeach</div>
<p class="muted">{{ $report['period'] }} · Generado {{ now()->format('d/m/Y g:i A') }}</p>
@if($f['report']==='balances')<p class="notice">Deja ambas fechas vacías para consultar todos los saldos pendientes. “Atrasadas” se refiere a la fecha de entrega, no a un plazo de crédito.</p>@endif
<div class="stat-grid">@foreach($report['stats'] as $label=>$value)<div class="stat"><span>{{ $label }}</span><strong>{{ $value }}</strong></div>@endforeach</div>
@foreach($report['tables'] as $table)<section class="card"><h2>{{ $table['title'] }}</h2><div class="table-wrap"><table><thead><tr>@foreach($table['headers'] as $heading)<th>{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($table['rows'] as $index=>$row)<tr>@foreach($row as $col=>$value)<td>@if($col===0 && isset($table['links'][$index]) && auth()->user()->can('orders.view'))<a href="{{ route('orders.show',$table['links'][$index]) }}"><strong>{{ $value }}</strong></a>@elseif(in_array($col,$table['money'],true))${{ number_format($value,2) }}@else{{ $value }}@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ count($table['headers']) }}" class="empty">Sin registros para estos filtros.</td></tr>@endforelse</tbody></table></div></section>@endforeach
</x-layouts.app>
