<?php
return [
 'required'=>'El campo :attribute es obligatorio.', 'required_if'=>'El campo :attribute es obligatorio para esta opción.',
 'string'=>'El campo :attribute debe ser texto.', 'numeric'=>'El campo :attribute debe ser numérico.', 'integer'=>'El campo :attribute debe ser un número entero.', 'decimal'=>'El campo :attribute admite hasta :max decimales.',
 'email'=>'Ingresa un correo electrónico válido.', 'unique'=>'El valor de :attribute ya está registrado.', 'exists'=>'La selección de :attribute no es válida.', 'in'=>'La selección de :attribute no es válida.', 'boolean'=>'El campo :attribute debe ser verdadero o falso.',
 'date'=>'Ingresa una fecha válida.', 'date_format'=>'El campo :attribute debe tener el formato :format.', 'after_or_equal'=>'El campo :attribute debe ser igual o posterior a :date.', 'array'=>'El campo :attribute debe ser una lista.', 'uuid'=>'La referencia de la operación no es válida.',
 'min'=>['numeric'=>'El campo :attribute debe ser al menos :min.','string'=>'El campo :attribute debe tener al menos :min caracteres.','array'=>'Selecciona al menos :min elementos en :attribute.'],
 'max'=>['numeric'=>'El campo :attribute no puede superar :max.','string'=>'El campo :attribute admite hasta :max caracteres.','array'=>'El campo :attribute admite hasta :max elementos.'],
 'attributes'=>['phone'=>'teléfono','date'=>'fecha de entrega','time'=>'hora de entrega','city'=>'ciudad','state'=>'estado','form.name'=>'nombre','form.price'=>'precio','form.category_id'=>'categoría','groups.*.name'=>'nombre del grupo','groups.*.max_choices'=>'máximo de elecciones','groups.*.option_ids'=>'opciones del grupo','customer_name'=>'cliente','customer_phone'=>'teléfono','delivery_address'=>'dirección','delivery_cost'=>'costo de envío','scheduled_date'=>'fecha de entrega','scheduled_time'=>'hora de entrega','items'=>'productos','items.*.quantity'=>'cantidad','items.*.options.*'=>'cantidad de botanas','payments.*.amount'=>'importe','email'=>'correo','password'=>'contraseña','name'=>'nombre','price'=>'precio','reason'=>'motivo','amount'=>'importe','initial'=>'fondo inicial','max_choices'=>'elecciones','hourly_limit'=>'límite por hora','daily_limit'=>'límite diario'],
];
