<div><div class="page-heading"><div><span class="eyebrow">PRODUCTOS Y MODIFICADORES</span><h1>Catálogo</h1><p class="muted">Organiza productos visibles y opciones auxiliares por categoría.</p></div><div class="action-row"><a class="secondary" href="{{ route('categories') }}">Categorías</a>@if(!$showEditor)<button class="primary" wire:click="create">＋ Nuevo producto</button>@else<button class="secondary" wire:click="cancel">Volver al catálogo</button>@endif</div></div>
@if(session('success'))<div class="notice success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="notice error" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
@if(!$showEditor)
<div class="filter-bar"><label>Buscar producto<input wire:model.live.debounce.300ms="search" placeholder="Nombre del producto"></label><label>Categoría<select wire:model.live="categoryFilter"><option value="">Todas las categorías</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}{{ !$c->visible_in_pos?' · Oculta en POS':'' }}</option>@endforeach</select></label><label>Estado<select wire:model.live="statusFilter"><option value="">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></label></div>
<div class="card table-wrap"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Disponibilidad</th><th></th></tr></thead><tbody>@forelse($products as $p)<tr><td><strong>{{ $p->name }}</strong><small class="muted">{{ $p->type==='compuesto'?'Con grupos de modificadores':'Simple' }} · {{ $p->printArea->name }}</small></td><td>{{ $p->category->name }}</td><td>${{ number_format($p->price,2) }}</td><td><span class="tag">{{ !$p->is_active?'Inactivo':($p->category->visible_in_pos?'Visible en POS':'Solo modificador') }}</span></td><td><button class="secondary" wire:click="edit({{ $p->id }})">Editar</button></td></tr>@empty<tr><td colspan="5" class="empty">No hay productos para este filtro.</td></tr>@endforelse</tbody></table></div>{{ $products->links() }}
@else
<form wire:submit="save"><div class="two-columns"><section class="card form-stack"><h2>{{ $productId?'Editar producto':'Nuevo producto' }}</h2><label>Nombre<input wire:model="form.name" required maxlength="150"></label><label>Precio de venta<input wire:model="form.price" type="number" min="0" step="0.01" required></label><label>Categoría<select wire:model="form.category_id"><option value="">Seleccionar categoría</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}{{ !$c->visible_in_pos?' · Oculta':'' }}</option>@endforeach</select></label><button type="button" class="secondary" wire:click="$toggle('showNewCategory')">＋ Crear categoría aquí</button>
@if($showNewCategory)<div class="inline-create"><label>Nombre de nueva categoría<input wire:model="newCategoryName" maxlength="100"></label><label class="check-label"><input type="checkbox" wire:model="newCategoryVisible"> Visible en punto de venta</label><button type="button" class="secondary" wire:click="createCategory">Crear y seleccionar</button></div>@endif
<label>Área de impresión<select wire:model="form.print_area_id">@foreach($areas as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select></label><label>Composición e incluidos<textarea wire:model="form.description" maxlength="3000" rows="3"></textarea></label><label>Tipo de producto<select wire:model.live="form.type"><option value="simple">Simple / composición fija</option><option value="compuesto">Compuesto / elegir modificadores</option></select></label><div class="field-grid"><label>Límite por hora<input type="number" min="0" wire:model="form.hourly_limit" required></label><label>Límite diario<input type="number" min="0" wire:model="form.daily_limit" required></label></div><p class="muted tiny">Cero significa sin límite de producción.</p><label class="check-label"><input type="checkbox" wire:model="form.is_active"> Producto activo</label></section>
<section>@if(($form['type']??'simple')==='compuesto')<div class="card"><h2>Grupos de modificadores</h2><p class="muted">Se muestran en el orden en que los agregas. Las opciones están incluidas en el precio del producto.</p><button class="secondary full" type="button" wire:click="addGroup">＋ Agregar grupo</button></div>
@foreach($groups as $i=>$group)<div class="card form-stack" wire:key="edit-group-{{ $i }}-{{ $group['id']??'new' }}"><div class="row-between"><h3>Grupo {{ $i+1 }}</h3><button class="danger" type="button" wire:click="removeGroup({{ $i }})">Quitar grupo</button></div><label>Pregunta / nombre del grupo<input wire:model="groups.{{ $i }}.name" placeholder="Ej. Término, Guarniciones, Botanas" maxlength="100" required></label><label>Máximo de elecciones en este grupo<input type="number" min="1" max="100" wire:model="groups.{{ $i }}.max_choices" required></label><label class="check-label"><input type="checkbox" wire:model="groups.{{ $i }}.required"> Forzar captura: completar exactamente el máximo</label><label>Filtrar opciones por categoría<select wire:model.live="groups.{{ $i }}.category_id"><option value="">Todas las categorías</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></label><p class="muted tiny">{{ count($group['option_ids']) }} opciones asignadas. Cambiar el filtro no quita las opciones ya seleccionadas.</p><div class="option-checklist">@forelse($auxiliaries->when($group['category_id'],fn($items)=>$items->where('category_id',$group['category_id'])) as $option)<label class="check-label"><input type="checkbox" wire:model.live="groups.{{ $i }}.option_ids" value="{{ $option->id }}">{{ $option->name }}</label>@empty<p class="muted">Crea primero productos simples activos en esta categoría.</p>@endforelse</div></div>@endforeach
@else<div class="card"><h2>Producto de composición fija</h2><p class="muted">Se agrega directamente al pedido. Selecciona “Compuesto” si necesita preguntas o botanas a elegir.</p></div>@endif</section></div><div class="editor-actions"><button type="button" class="secondary" wire:click="cancel">Cancelar</button><button class="primary" wire:loading.attr="disabled">Guardar producto →</button></div></form>
@endif</div>
