<div>
<div class="page-heading"><div><span class="eyebrow">UNA BUENA COMIDA EMPIEZA AQUÍ</span><h1>Nuevo pedido</h1><p class="muted">Cliente → Entrega → Productos y pago</p></div><a class="pill {{ $shift?'green':'amber' }}" href="{{ route('cash') }}">● {{ $shift?'Caja abierta · #'.$shift->id:'Caja cerrada · Abrir turno' }}</a></div>
@if($stage !== 'pos' && $errors->any())<div class="notice error" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
@if($stage==='customer')
<section wire:key="customer-step" class="card wizard-card pos-customer-entry"><span class="eyebrow">PASO 1 DE 3</span><h2>¿Para quién es el pedido?</h2>
<div x-ref="customerLookup" x-data="{ open: true, active: -1, options() { return Array.from(this.$refs.customerLookup.querySelectorAll('[data-customer-option]')); }, move(step) { const rows = this.options(); if (!rows.length) return; this.open = true; this.active = this.active &lt; 0 ? (step > 0 ? 0 : rows.length - 1) : (this.active + step + rows.length) % rows.length; this.$nextTick(() => rows[this.active]?.scrollIntoView({block:'nearest'})); }, choose() { if (!this.open) return; const row = this.options()[this.active]; if (row) row.click(); } }" @click.outside="open = false" @keydown.escape.stop="open = false; active = -1">
<label>Buscar cliente por nombre o teléfono<input wire:model.live.debounce.300ms="customerSearch" placeholder="Escribe un nombre o teléfono" autocomplete="off" role="combobox" aria-autocomplete="list" aria-controls="customer-search-results" :aria-expanded="open &amp;&amp; options().length > 0" :aria-activedescendant="open &amp;&amp; active >= 0 ? options()[active]?.id : null" @input="open = true; active = -1" @keydown.arrow-down.prevent="move(1)" @keydown.arrow-up.prevent="move(-1)" @keydown.enter.prevent="choose()" @keydown.tab="open = false"></label>
@if(!$customerId && $matches->isNotEmpty())<div id="customer-search-results" role="listbox" aria-label="Clientes encontrados" class="customer-results" x-show="open" wire:key="customer-results-{{ md5($customerSearch) }}">@foreach($matches as $match)<button id="customer-option-{{ $match->id }}" data-customer-option type="button" role="option" tabindex="-1" :aria-selected="active === {{ $loop->index }}" :class="{ 'customer-result-active': active === {{ $loop->index }} }" class="customer-result" @mouseenter="active = {{ $loop->index }}" @click="open = false; active = -1" wire:click="selectCustomer({{ $match->id }})"><strong>{{ $match->name }}</strong><span>{{ $match->phone }} · {{ $match->neighborhood }}</span></button>@endforeach</div>
@elseif(!$customerId && mb_strlen(trim($customerSearch))>=2)<p class="notice" x-show="open">No encontramos coincidencias. Completa los datos para registrar al cliente.</p>@endif
</div>
<div class="row-between" style="margin:20px 0"><h3>{{ $customerId?'Actualizar cliente seleccionado':'Registrar nuevo cliente' }}</h3>@if($customerId)<button class="secondary" wire:click="newCustomer">Otro cliente</button>@endif</div>
<form wire:submit="saveCustomer" class="form-stack">@include('partials.customer-fields')<button class="primary full" wire:loading.attr="disabled">Guardar cliente y continuar →</button></form>
</section>
@elseif($stage==='schedule')
<section wire:key="schedule-step" class="card wizard-card"><span class="eyebrow">PASO 2 DE 3</span><h2>¿Cuándo y cómo se entrega?</h2><div class="customer-summary"><strong>{{ $customer?->name }}</strong><span>{{ $customer?->phone }}</span><button class="link-button" wire:click="editCustomer">Editar cliente</button></div>
<form wire:submit="confirmSchedule" class="form-stack"><div class="field-grid"><label>Fecha de entrega *<input type="date" wire:model.live="dateInput" required min="{{ now()->toDateString() }}"></label><label>Hora de entrega *<input type="time" wire:model.live="timeInput" required></label></div><label>Tipo de entrega<select wire:model.live="delivery_type"><option value="sucursal">Recoger en sucursal</option><option value="domicilio">A domicilio</option></select></label>
@if($delivery_type==='domicilio')<p class="notice">{{ $customer?->address() }}</p><label>Costo de envío<input type="number" min="0" step="0.01" wire:model="delivery_cost" required></label>@endif
@can('production.override')<label class="check-label"><input type="checkbox" wire:model="override"> Autorizar sobrecarga por hora (no diaria)</label>@endcan
<p class="muted">Confirma el horario para revisar la capacidad de producción al agregar cada producto.</p><button class="primary full" wire:loading.attr="disabled">Continuar al punto de venta →</button></form></section>
@else
<div wire:key="sale-context" class="order-context"><div><small>CLIENTE</small><strong>{{ $customer?->name }}</strong><span>{{ $customer?->phone }}</span><button class="link-button" wire:click="editCustomer">Editar</button></div><div><small>ENTREGA</small><strong>{{ \Carbon\Carbon::parse($scheduled_date)->format('d/m/Y') }} · {{ $scheduled_time }}</strong><span>{{ $delivery_type==='domicilio'?'A domicilio':'Recoger en sucursal' }}</span><button class="link-button" wire:click="editSchedule">Cambiar</button></div></div>
<div wire:key="sale-step" class="pos-grid"><section><div class="search-wrap"><span>⌕</span><input aria-label="Buscar producto" wire:model.live.debounce.300ms="search" placeholder="Buscar charola, plato o producto..."></div><div class="tabs"><button wire:click="$set('category','')" class="{{ $category===''?'selected':'' }}">Todo el menú</button>@foreach($categories as $c)<button wire:click="$set('category','{{ $c->id }}')" class="{{ $category==$c->id?'selected':'' }}">{{ $c->name }}</button>@endforeach</div>
<div class="product-grid">@forelse($catalog as $p)<button class="product-card" wire:click="add({{ $p->id }})" wire:loading.attr="disabled" wire:key="product-{{ $p->id }}"><div class="product-art art-{{ $p->category_id % 3 }}"><span>{{ $p->type==='compuesto'?'◉':'◌' }}</span><small>{{ $p->category->name }}</small></div><div class="product-info"><span class="muted tiny">{{ $p->type==='compuesto'?'PERSONALIZAR':'COMPOSICIÓN FIJA' }}</span><h3>{{ $p->name }}</h3><div class="price-line"><strong>${{ number_format($p->price,2) }}</strong><span class="add-icon">＋</span></div>@if($p->hourly_limit || $p->daily_limit)<small class="muted">Límite: {{ $p->hourly_limit ?: '∞' }}/hora · {{ $p->daily_limit ?: '∞' }}/día</small>@endif</div></button>@empty<div class="empty">No hay productos disponibles para esta búsqueda.</div>@endforelse</div></section>
<aside class="order-panel"><div class="panel-title"><h2>Tu pedido</h2><span class="count">{{ count($items) }}</span></div><div class="order-lines">
@forelse($items as $index=>$item) @php($p=$selected->get($item['product_id']))
@if($p)<div class="order-line" wire:key="line-{{ $index }}-{{ $p->id }}"><div class="row-between"><strong>{{ $p->name }}</strong><button class="remove" aria-label="Quitar {{ $p->name }}" wire:click="remove({{ $index }})">×</button></div><div class="row-between"><div class="quantity-buttons"><button wire:click="quantity({{ $index }},-1)" aria-label="Disminuir {{ $p->name }}" @disabled($item['quantity']<=1)>−</button><b>{{ $item['quantity'] }}</b><button wire:click="quantity({{ $index }},1)" aria-label="Aumentar {{ $p->name }}">＋</button></div><strong>${{ number_format($p->price*$item['quantity'],2) }}</strong></div>@foreach($item['summary']??[] as $option)<p class="muted tiny">{{ $option['group'] }}: {{ $option['quantity'] }} × {{ $option['name'] }}</p>@endforeach
@if($item['notes'])<p class="muted">{{ $item['notes'] }}</p>@endif
<button class="link-button" wire:click="editItem({{ $index }})">{{ $p->type==='compuesto'?'Editar selección / notas':'Agregar notas' }}</button></div>@endif
@empty<div class="empty cart-empty"><h3>Selecciona productos del menú</h3><p>Validaremos la capacidad con el horario que elegiste.</p></div>@endforelse
</div><form wire:submit="save" class="checkout" novalidate>@can('production.override')<label class="check-label"><input type="checkbox" wire:model="override"> Autorizar sobrecarga por hora (no diaria)</label>@endcan
@if($delivery_type==='domicilio')<p class="muted tiny">{{ $customer?->address() }}</p><label>Costo de envío<input type="number" min="0" step="0.01" wire:model.live="delivery_cost" required></label><label>Repartidor *<select wire:model="delivery_driver_id" required><option value="">Selecciona un repartidor</option>@foreach($drivers as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select></label>@if($drivers->isEmpty())<p class="notice error">No hay repartidores activos. Solicita su registro antes de confirmar la entrega a domicilio.</p>@endif @endif
<div class="total-row"><span>Total del pedido</span><strong>${{ number_format($total,2) }}</strong></div><h3>Pago inicial / anticipo</h3><p class="muted tiny">Combina métodos o deja en cero para cobrar después.</p><div class="payment-grid">@foreach($payments as $method=>$value)<label>{{ ucfirst($method) }}<input type="number" min="0" step="10" wire:model.live="payments.{{ $method }}"></label>@endforeach</div><div class="row-between muted"><span>Saldo pendiente</span><b>${{ number_format(max(0,$total-array_sum(array_map('floatval',$payments))),2) }}</b></div><button class="primary full" type="submit" wire:loading.attr="disabled" @disabled(!$shift||!$items)>Confirmar pedido →</button>
@if(!$modalProduct && $errors->any())<div id="order-confirmation-errors" class="notice error" role="alert" aria-live="assertive" x-data x-init="$nextTick(() => $el.scrollIntoView({block: 'nearest', behavior: 'smooth'}))"><strong>No se pudo confirmar el pedido</strong>@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
</form></aside></div>
@endif
@if($modalProduct)
<div wire:key="modifier-modal-{{ $modalProduct->id }}" class="modal-backdrop" x-data @keydown.escape.window="$wire.closeModifiers()"><section class="modal-dialog" role="dialog" aria-modal="true" aria-labelledby="modifier-title" tabindex="-1" x-init="$el.focus()"><header class="row-between"><div><span class="eyebrow">PERSONALIZA TU PEDIDO</span><h2 id="modifier-title">{{ $modalProduct->name }}</h2><p class="muted">${{ number_format($modalProduct->price,2) }} · Las selecciones no cambian el precio</p></div><button class="remove" wire:click="closeModifiers" aria-label="Cerrar selección">×</button></header>
@if($errors->any())<div class="notice error" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
@if($modalProduct->description)<p class="muted" style="margin:16px 0">{{ $modalProduct->description }}</p>@endif
@foreach($modalProduct->modifierGroups as $group)<section class="modifier-group" wire:key="group-{{ $group->id }}"><div class="row-between"><h3>{{ $group->name }}</h3><span class="pill {{ array_sum($modifiers[$group->id]??[])==$group->max_choices?'green':'amber' }}">{{ array_sum($modifiers[$group->id]??[]) }}/{{ $group->max_choices }}</span></div><p class="muted tiny">{{ $group->required?'Obligatorio: elige exactamente':'Opcional: elige hasta' }} {{ $group->max_choices }}. @if($group->max_choices>1)Puedes repetir opciones.@endif</p><div class="modifier-options">@foreach($group->options->where('is_active',true) as $option)@php($count=$modifiers[$group->id][$option->id]??0)<div class="modifier-choice {{ $count?'chosen':'' }}"><button wire:click="option({{ $group->id }},{{ $option->id }},1)" wire:loading.attr="disabled"><span>{{ $option->name }}</span><b>{{ $count ?: '＋' }}</b></button>@if($count)<button class="subtract-option" aria-label="Quitar {{ $option->name }}" wire:click="option({{ $group->id }},{{ $option->id }},-1)">−</button>@endif</div>@endforeach</div></section>@endforeach
<label>Notas de preparación<textarea wire:model="draftNotes" maxlength="1000" rows="2" placeholder="Sin cebolla, indicaciones de preparación..."></textarea></label><footer class="modal-footer"><button class="secondary" wire:click="closeModifiers">Cancelar</button><button class="primary" wire:click="confirmModifiers" wire:loading.attr="disabled">{{ $editingIndex===null?'Agregar al pedido':'Guardar selección' }} →</button></footer></section></div>
@endif
</div>
